### ISSUE TITLE
solanaTransfer does not use callback

### ISSUE THREAD

**Issue by TangHaiBo1** [Elizabet1926/SolanaWallet#1]
solanaTransfer does not use callback
<img width="693" alt="image" src="https://github.com/user-attachments/assets/aec93cab-900d-45e7-b16a-03a8faa324b9">

**Comment by TangHaiBo1** [comment]
SolanaMainNet is our own node

**Comment by Elizabet1926** [comment]
Today, I used the node "https://solana.maiziqianbao.net/" to test SOL transfers and SPL Token transfers, both of which were successful. However, SPL Token transfers using this node are relatively slow, taking about 20 seconds. Therefore, I recommend purchasing nodes from https://www.quicknode.com/. The latest demo now uses the node "https://solana.maiziqianbao.net/." You can download the latest demo to check it out.
